[libraries]

lib6.files = [
	'reg_test.vhd',
]

lib5.files = [
	'let_selection.vhd',
]

lib4.files = [
	'shy_reg.vhd',
]

lib3.files = [
	'counter.vhd',
]

lib2.files = [
	'counter_k.vhd',
]
lib1.files = [
	'register_g.vhd',
]