[libraries]

lib7.files = [
	'morse_fpga.vhd',
]

lib6.files = [
	'input_unit.vhd',
]

lib5.files = [
	'logic_unit.vhd',
]

lib4.files = [
	'proc_symbol.vhd',
]

lib3.files = [
	'shift_symbol.vhd',
]

lib2.files = [
	'counter.vhd',
]

lib1.files = [
	'register_g.vhd',
]